markdown: rdiscount
safe: true
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - README.md
  - config.rb
permalink: :title

# Site configuration
baseurl: https://secondfriend.github.io/
url: https://secondfriend.github.io
domain: secondfriend.github.io
title: 2ndFriend
subtitle: A secure, anonymous and confidential channel of communication between a young person and a trusted counselor
author: Florian Rathgeber
email: hello@2ndfriend.io
feedurl: atom.xml
analytics_id: UA-35633433-1
